export const MAX_LEVEL = 10;

export const XP_THRESHOLDS = {
  2: 300,
  3: 700,
  4: 1300,
  5: 2000,
  6: 3000,
  7: 4200,
  8: 5600,
  9: 7200,
  10: 9000,
};

export const CARD_LEVELS = [2, 4, 5, 6, 7, 8, 10];

export const PATHS = {
  power: { id: 'power', label: 'Power', category: 'power' },
  survival: { id: 'survival', label: 'Survival', category: 'survival' },
  mobility: { id: 'mobility', label: 'Mobility', category: 'mobility' },
  style: { id: 'style', label: 'Style', category: 'style' },
};

export const DEFAULT_MODIFIERS = {
  damageMult: 0,
  speedMult: 0,
  maxHpBonus: 0,
  maxManaBonus: 0,
  dodgeIFrameBonus: 0,
  cooldownMult: 0,
  surgeGainMult: 0,
  essenceGainMult: 0,
  statusDamageMult: 0,
  spellDamageMult: 0,
  auraScale: 0,
  cosmeticAura: null,
  lifesteal: 0,
  secondWind: false,
};

const GENERIC_STAT_CARDS = [
  {
    id: 'stat-sharpened-edge',
    name: 'Sharpened Edge',
    type: 'stat',
    category: 'power',
    description: '+12% attack damage this run.',
    effect: { modifiers: { damageMult: 0.12 } },
  },
  {
    id: 'stat-swift-soles',
    name: 'Swift Soles',
    type: 'stat',
    category: 'mobility',
    description: '+12% movement speed this run.',
    effect: { modifiers: { speedMult: 0.12 } },
  },
  {
    id: 'stat-iron-skin',
    name: 'Iron Skin',
    type: 'stat',
    category: 'survival',
    description: '+120 max HP and restore that amount.',
    effect: { modifiers: { maxHpBonus: 120 }, heal: 120 },
  },
  {
    id: 'stat-mana-shard',
    name: 'Mana Shard',
    type: 'stat',
    category: 'style',
    description: '+30 max Mana and restore that amount.',
    effect: { modifiers: { maxManaBonus: 30 }, mana: 30 },
  },
];

const PASSIVE_CARDS = [
  {
    id: 'passive-bleed-hunger',
    name: 'Bleed Hunger',
    type: 'passive',
    category: 'survival',
    hunterId: 'dabik',
    description: 'Light attacks restore a small amount on hit.',
    effect: { modifiers: { lifesteal: 0.03 } },
  },
  {
    id: 'passive-iron-resolve',
    name: 'Iron Resolve',
    type: 'passive',
    category: 'survival',
    hunterId: 'benzu',
    description: '+160 max HP and stronger survival scaling.',
    effect: { modifiers: { maxHpBonus: 160 }, heal: 160 },
  },
  {
    id: 'passive-speed-read',
    name: 'Speed Read',
    type: 'passive',
    category: 'mobility',
    hunterId: 'sereisa',
    description: '+1 dodge iframe and +8% movement speed.',
    effect: { modifiers: { dodgeIFrameBonus: 1, speedMult: 0.08 } },
  },
  {
    id: 'passive-mana-loop',
    name: 'Mana Loop',
    type: 'passive',
    category: 'style',
    hunterId: 'vesol',
    description: '+15% spell damage and +20 max Mana.',
    effect: { modifiers: { spellDamageMult: 0.15, maxManaBonus: 20 }, mana: 20 },
  },
  {
    id: 'passive-combo-memory',
    name: 'Combo Memory',
    type: 'passive',
    category: 'style',
    description: '+10% damage and +10% Surge gain.',
    effect: { modifiers: { damageMult: 0.1, surgeGainMult: 0.1 } },
  },
  {
    id: 'passive-essence-surge',
    name: 'Essence Surge',
    type: 'passive',
    category: 'utility',
    description: '+20% Essence gained from future rewards.',
    effect: { modifiers: { essenceGainMult: 0.2 } },
  },
];

const SPELL_MOD_CARDS = [
  {
    id: 'dabik-phantom-trail',
    name: 'Phantom Trail',
    type: 'spell-mod',
    category: 'power',
    hunterId: 'dabik',
    level: 4,
    description: 'Shadow Step leaves a stronger bleed opening.',
    effect: { minorMod: 'phantom-trail', modifiers: { statusDamageMult: 0.15 } },
  },
  {
    id: 'dabik-double-blink',
    name: 'Double Blink',
    type: 'spell-mod',
    category: 'mobility',
    hunterId: 'dabik',
    level: 4,
    description: 'Shadow Step sharpens mobility and cooldown flow.',
    effect: { minorMod: 'double-blink', modifiers: { cooldownMult: -0.08, speedMult: 0.08 } },
  },
  {
    id: 'dabik-soul-siphon',
    name: 'Soul Siphon',
    type: 'spell-mod',
    category: 'survival',
    hunterId: 'dabik',
    level: 4,
    description: 'Blinking feeds survival through lifesteal.',
    effect: { minorMod: 'soul-siphon', modifiers: { lifesteal: 0.04 } },
  },
  {
    id: 'dabik-mirror-fight',
    name: 'Mirror Fight',
    type: 'spell-mod',
    category: 'power',
    hunterId: 'dabik',
    level: 6,
    description: 'Shadow Clone increases total attack pressure.',
    effect: { advancedMod: 'mirror-fight', modifiers: { damageMult: 0.12 } },
  },
  {
    id: 'dabik-twin-veil',
    name: 'Twin Veil',
    type: 'spell-mod',
    category: 'style',
    hunterId: 'dabik',
    level: 6,
    description: 'Clone play improves Surge and aura growth.',
    effect: { advancedMod: 'twin-veil', modifiers: { surgeGainMult: 0.15, auraScale: 0.1 } },
  },
  {
    id: 'dabik-death-mark',
    name: 'Death Mark',
    type: 'spell-mod',
    category: 'power',
    hunterId: 'dabik',
    level: 6,
    description: 'Marked enemies take stronger status damage.',
    effect: { advancedMod: 'death-mark', modifiers: { statusDamageMult: 0.2 } },
  },
  {
    id: 'benzu-thunder-clap',
    name: 'Thunder Clap',
    type: 'spell-mod',
    category: 'power',
    hunterId: 'benzu',
    level: 4,
    description: 'Shield Bash hits harder and controls space.',
    effect: { minorMod: 'thunder-clap', modifiers: { damageMult: 0.1 } },
  },
  {
    id: 'benzu-iron-counter',
    name: 'Iron Counter',
    type: 'spell-mod',
    category: 'survival',
    hunterId: 'benzu',
    level: 4,
    description: 'Counter timing adds armor and HP.',
    effect: { minorMod: 'iron-counter', modifiers: { maxHpBonus: 140 }, heal: 140 },
  },
  {
    id: 'benzu-quake-step',
    name: 'Quake Step',
    type: 'spell-mod',
    category: 'mobility',
    hunterId: 'benzu',
    level: 4,
    description: 'Bash recovery improves movement flow.',
    effect: { minorMod: 'quake-step', modifiers: { speedMult: 0.08, dodgeIFrameBonus: 1 } },
  },
  {
    id: 'benzu-aftershock',
    name: 'Aftershock',
    type: 'spell-mod',
    category: 'power',
    hunterId: 'benzu',
    level: 6,
    description: 'Seismic Slam improves attack damage.',
    effect: { advancedMod: 'aftershock', modifiers: { damageMult: 0.14 } },
  },
  {
    id: 'benzu-crater-zone',
    name: 'Crater Zone',
    type: 'spell-mod',
    category: 'style',
    hunterId: 'benzu',
    level: 6,
    description: 'Slam zones improve status pressure.',
    effect: { advancedMod: 'crater-zone', modifiers: { statusDamageMult: 0.18 } },
  },
  {
    id: 'benzu-boulder-drop',
    name: 'Boulder Drop',
    type: 'spell-mod',
    category: 'survival',
    hunterId: 'benzu',
    level: 6,
    description: 'Heavy spell timing adds defensive value.',
    effect: { advancedMod: 'boulder-drop', modifiers: { maxHpBonus: 100, cooldownMult: -0.06 }, heal: 100 },
  },
  {
    id: 'sereisa-volt-burst',
    name: 'Volt Burst',
    type: 'spell-mod',
    category: 'power',
    hunterId: 'sereisa',
    level: 4,
    description: 'Electric Dart improves burst damage.',
    effect: { minorMod: 'volt-burst', modifiers: { spellDamageMult: 0.15 } },
  },
  {
    id: 'sereisa-overcharge',
    name: 'Overcharge',
    type: 'spell-mod',
    category: 'style',
    hunterId: 'sereisa',
    level: 4,
    description: 'Charged darts improve Surge generation.',
    effect: { minorMod: 'overcharge', modifiers: { surgeGainMult: 0.18 } },
  },
  {
    id: 'sereisa-ricochet',
    name: 'Ricochet',
    type: 'spell-mod',
    category: 'mobility',
    hunterId: 'sereisa',
    level: 4,
    description: 'Dart flow increases speed and cooldown pace.',
    effect: { minorMod: 'ricochet', modifiers: { speedMult: 0.08, cooldownMult: -0.06 } },
  },
  {
    id: 'sereisa-storm-net',
    name: 'Storm Net',
    type: 'spell-mod',
    category: 'power',
    hunterId: 'sereisa',
    level: 6,
    description: 'Chain Shock increases spell damage.',
    effect: { advancedMod: 'storm-net', modifiers: { spellDamageMult: 0.18 } },
  },
  {
    id: 'sereisa-overclock',
    name: 'Overclock',
    type: 'spell-mod',
    category: 'style',
    hunterId: 'sereisa',
    level: 6,
    description: 'Shocked enemies feed aura escalation.',
    effect: { advancedMod: 'overclock', modifiers: { auraScale: 0.12, statusDamageMult: 0.12 } },
  },
  {
    id: 'sereisa-grounding-wire',
    name: 'Grounding Wire',
    type: 'spell-mod',
    category: 'survival',
    hunterId: 'sereisa',
    level: 6,
    description: 'Control play adds safety and i-frames.',
    effect: { advancedMod: 'grounding-wire', modifiers: { dodgeIFrameBonus: 2 } },
  },
  {
    id: 'vesol-piercing-bolt',
    name: 'Piercing Bolt',
    type: 'spell-mod',
    category: 'power',
    hunterId: 'vesol',
    level: 4,
    description: 'Flame Bolt improves spell damage.',
    effect: { minorMod: 'piercing-bolt', modifiers: { spellDamageMult: 0.16 } },
  },
  {
    id: 'vesol-charged-shot',
    name: 'Charged Shot',
    type: 'spell-mod',
    category: 'style',
    hunterId: 'vesol',
    level: 4,
    description: 'Flame Bolt improves mana efficiency.',
    effect: { minorMod: 'charged-shot', modifiers: { cooldownMult: -0.08, maxManaBonus: 20 }, mana: 20 },
  },
  {
    id: 'vesol-scattershot',
    name: 'Scattershot',
    type: 'spell-mod',
    category: 'power',
    hunterId: 'vesol',
    level: 4,
    description: 'More bolts increase burn pressure.',
    effect: { minorMod: 'scattershot', modifiers: { statusDamageMult: 0.15 } },
  },
  {
    id: 'vesol-afterburn',
    name: 'Afterburn',
    type: 'spell-mod',
    category: 'power',
    hunterId: 'vesol',
    level: 6,
    description: 'Flame Wall strengthens burn ticks.',
    effect: { advancedMod: 'afterburn', modifiers: { statusDamageMult: 0.2 } },
  },
  {
    id: 'vesol-double-wall',
    name: 'Double Wall',
    type: 'spell-mod',
    category: 'style',
    hunterId: 'vesol',
    level: 6,
    description: 'Wall control improves spell rhythm.',
    effect: { advancedMod: 'double-wall', modifiers: { spellDamageMult: 0.12, cooldownMult: -0.08 } },
  },
  {
    id: 'vesol-inferno-gate',
    name: 'Inferno Gate',
    type: 'spell-mod',
    category: 'survival',
    hunterId: 'vesol',
    level: 6,
    description: 'The wall becomes safer to build around.',
    effect: { advancedMod: 'inferno-gate', modifiers: { maxHpBonus: 80, lifesteal: 0.02 }, heal: 80 },
  },
];

const PATH_LOCK_CARDS = [
  {
    id: 'path-power',
    name: 'Power Path',
    type: 'path-lock',
    category: 'power',
    level: 7,
    description: 'Lock into damage, status pressure, and execution.',
    effect: { upgradePath: 'power', modifiers: { damageMult: 0.12 } },
  },
  {
    id: 'path-survival',
    name: 'Survival Path',
    type: 'path-lock',
    category: 'survival',
    level: 7,
    description: 'Lock into healing, armor, and second chances.',
    effect: { upgradePath: 'survival', modifiers: { maxHpBonus: 180 }, heal: 180 },
  },
  {
    id: 'path-mobility',
    name: 'Mobility Path',
    type: 'path-lock',
    category: 'mobility',
    level: 7,
    description: 'Lock into speed, dodge flow, and i-frames.',
    effect: { upgradePath: 'mobility', modifiers: { speedMult: 0.14, dodgeIFrameBonus: 2 } },
  },
  {
    id: 'path-style',
    name: 'Style Path',
    type: 'path-lock',
    category: 'style',
    level: 7,
    description: 'Lock into spell synergy, aura growth, and crit flow.',
    effect: { upgradePath: 'style', modifiers: { auraScale: 0.15, surgeGainMult: 0.12 } },
  },
];

const PATH_UPGRADE_CARDS = [
  {
    id: 'path-power-relentless',
    name: 'Relentless',
    type: 'path-upgrade',
    category: 'power',
    path: 'power',
    level: 8,
    description: '+18% damage and stronger status ticks.',
    effect: { modifiers: { damageMult: 0.18, statusDamageMult: 0.12 } },
  },
  {
    id: 'path-power-execute-threshold',
    name: 'Execute Threshold',
    type: 'path-upgrade',
    category: 'power',
    path: 'power',
    level: 8,
    description: '+25% damage against weakened enemies.',
    effect: { modifiers: { damageMult: 0.2 } },
  },
  {
    id: 'path-power-status-amp',
    name: 'Status Amp',
    type: 'path-upgrade',
    category: 'power',
    path: 'power',
    level: 8,
    description: 'All status effects deal much more damage.',
    effect: { modifiers: { statusDamageMult: 0.25 } },
  },
  {
    id: 'path-survival-shield-rune',
    name: 'Shield Rune',
    type: 'path-upgrade',
    category: 'survival',
    path: 'survival',
    level: 8,
    description: '+220 max HP.',
    effect: { modifiers: { maxHpBonus: 220 }, heal: 220 },
  },
  {
    id: 'path-survival-lifesteal',
    name: 'Lifesteal',
    type: 'path-upgrade',
    category: 'survival',
    path: 'survival',
    level: 8,
    description: 'Light attacks restore health.',
    effect: { modifiers: { lifesteal: 0.05 } },
  },
  {
    id: 'path-survival-second-wind',
    name: 'Second Wind',
    type: 'path-upgrade',
    category: 'survival',
    path: 'survival',
    level: 8,
    description: 'Prepare one survival recovery per zone.',
    effect: { modifiers: { secondWind: true } },
  },
  {
    id: 'path-mobility-extra-dodge',
    name: 'Extra Dodge',
    type: 'path-upgrade',
    category: 'mobility',
    path: 'mobility',
    level: 8,
    description: '+4 dodge i-frames.',
    effect: { modifiers: { dodgeIFrameBonus: 4 } },
  },
  {
    id: 'path-mobility-slipstream',
    name: 'Slipstream',
    type: 'path-upgrade',
    category: 'mobility',
    path: 'mobility',
    level: 8,
    description: '+18% speed and +10% Surge gain.',
    effect: { modifiers: { speedMult: 0.18, surgeGainMult: 0.1 } },
  },
  {
    id: 'path-mobility-cooldown-cut',
    name: 'Cooldown Cut',
    type: 'path-upgrade',
    category: 'mobility',
    path: 'mobility',
    level: 8,
    description: 'Spells recover 14% faster.',
    effect: { modifiers: { cooldownMult: -0.14 } },
  },
  {
    id: 'path-style-spell-weave',
    name: 'Spell Weave',
    type: 'path-upgrade',
    category: 'style',
    path: 'style',
    level: 8,
    description: '+20% spell damage.',
    effect: { modifiers: { spellDamageMult: 0.2 } },
  },
  {
    id: 'path-style-aura-blaze',
    name: 'Aura Blaze',
    type: 'path-upgrade',
    category: 'style',
    path: 'style',
    level: 8,
    description: 'Aura grows and Essence gain improves.',
    effect: { modifiers: { auraScale: 0.22, essenceGainMult: 0.1 } },
  },
  {
    id: 'path-style-silent-casting',
    name: 'Silent Casting',
    type: 'path-upgrade',
    category: 'style',
    path: 'style',
    level: 8,
    description: 'Spells recover faster and hit harder.',
    effect: { modifiers: { cooldownMult: -0.1, spellDamageMult: 0.1 } },
  },
];

const CAPSTONE_CARDS = [
  {
    id: 'capstone-power',
    name: 'Overwhelming Finish',
    type: 'capstone',
    category: 'power',
    path: 'power',
    level: 10,
    description: 'Capstone: +25% damage and +25% status damage.',
    effect: { modifiers: { damageMult: 0.25, statusDamageMult: 0.25 } },
  },
  {
    id: 'capstone-survival',
    name: 'Last Stand',
    type: 'capstone',
    category: 'survival',
    path: 'survival',
    level: 10,
    description: 'Capstone: huge HP gain and second wind.',
    effect: { modifiers: { maxHpBonus: 300, secondWind: true }, heal: 300 },
  },
  {
    id: 'capstone-mobility',
    name: 'Phase Step',
    type: 'capstone',
    category: 'mobility',
    path: 'mobility',
    level: 10,
    description: 'Capstone: major speed and dodge i-frame gain.',
    effect: { modifiers: { speedMult: 0.25, dodgeIFrameBonus: 6 } },
  },
  {
    id: 'capstone-style',
    name: 'Transcend',
    type: 'capstone',
    category: 'style',
    path: 'style',
    level: 10,
    description: 'Capstone: spell, Surge, and aura escalation.',
    effect: { modifiers: { spellDamageMult: 0.3, surgeGainMult: 0.25, auraScale: 0.3 } },
  },
];

export const CARD_POOL = [
  ...GENERIC_STAT_CARDS,
  ...PASSIVE_CARDS,
  ...SPELL_MOD_CARDS,
  ...PATH_LOCK_CARDS,
  ...PATH_UPGRADE_CARDS,
  ...CAPSTONE_CARDS,
];

export const SHOP_ITEMS = [
  {
    id: 'sharpened-edge',
    name: 'Sharpened Edge',
    category: 'power',
    cost: 80,
    tier: 1,
    description: '+15% light and heavy attack damage.',
    effect: { modifiers: { damageMult: 0.15 } },
  },
  {
    id: 'brutal-finisher',
    name: 'Brutal Finisher',
    category: 'power',
    cost: 120,
    tier: 2,
    description: '+20% attack damage.',
    effect: { modifiers: { damageMult: 0.2 } },
  },
  {
    id: 'elemental-amp',
    name: 'Elemental Amp',
    category: 'power',
    cost: 150,
    tier: 3,
    description: 'Status effects deal 20% more damage.',
    effect: { modifiers: { statusDamageMult: 0.2 } },
  },
  {
    id: 'potion',
    name: 'Potion',
    category: 'survival',
    cost: 60,
    tier: 1,
    consumable: true,
    description: 'Restore 200 HP immediately.',
    effect: { heal: 200 },
  },
  {
    id: 'iron-skin-shop',
    name: 'Iron Skin',
    category: 'survival',
    cost: 90,
    tier: 1,
    description: '+150 max HP and restore that amount.',
    effect: { modifiers: { maxHpBonus: 150 }, heal: 150 },
  },
  {
    id: 'second-wind-shop',
    name: 'Second Wind',
    category: 'survival',
    cost: 160,
    tier: 3,
    description: 'Prepare one survival recovery per zone.',
    effect: { modifiers: { secondWind: true } },
  },
  {
    id: 'swift-soles-shop',
    name: 'Swift Soles',
    category: 'mobility',
    cost: 80,
    tier: 1,
    description: '+15% movement speed.',
    effect: { modifiers: { speedMult: 0.15 } },
  },
  {
    id: 'blink-dust',
    name: 'Blink Dust',
    category: 'mobility',
    cost: 100,
    tier: 2,
    description: '+3 dodge i-frames.',
    effect: { modifiers: { dodgeIFrameBonus: 3 } },
  },
  {
    id: 'cooldown-crystal',
    name: 'Cooldown Crystal',
    category: 'mobility',
    cost: 120,
    tier: 2,
    description: 'Spells recover 15% faster.',
    effect: { modifiers: { cooldownMult: -0.15 } },
  },
  {
    id: 'mana-overflow',
    name: 'Mana Overflow',
    category: 'spell',
    cost: 90,
    tier: 2,
    requiresLevel: 3,
    description: '+40 max Mana and restore it.',
    effect: { modifiers: { maxManaBonus: 40 }, mana: 40 },
  },
  {
    id: 'spell-echo',
    name: 'Spell Echo',
    category: 'spell',
    cost: 140,
    tier: 2,
    requiresLevel: 3,
    description: '+20% spell damage.',
    effect: { modifiers: { spellDamageMult: 0.2 } },
  },
  {
    id: 'surge-accelerant',
    name: 'Surge Accelerant',
    category: 'spell',
    cost: 120,
    tier: 2,
    requiresLevel: 3,
    description: 'Surge fills 25% faster.',
    effect: { modifiers: { surgeGainMult: 0.25 } },
  },
  {
    id: 'reroll-token',
    name: 'Reroll Token',
    category: 'utility',
    cost: 30,
    tier: 1,
    consumable: true,
    description: 'Cheap utility buy: +10% Essence gain.',
    effect: { modifiers: { essenceGainMult: 0.1 } },
  },
  {
    id: 'essence-magnet',
    name: 'Essence Magnet',
    category: 'utility',
    cost: 80,
    tier: 1,
    description: '+20% future Essence gains.',
    effect: { modifiers: { essenceGainMult: 0.2 } },
  },
  {
    id: 'surge-catalyst',
    name: 'Surge Catalyst',
    category: 'utility',
    cost: 90,
    tier: 2,
    description: '+20% Surge gain.',
    effect: { modifiers: { surgeGainMult: 0.2 } },
  },
  {
    id: 'shadow-kunai',
    name: 'Shadow Kunai',
    category: 'weapon',
    cost: 65,
    tier: 1,
    hunterAffinity: 'dabik',
    description: 'Slot 2 weapon. +8% damage.',
    effect: { slot2WeaponId: 'shadow-kunai', modifiers: { damageMult: 0.08 } },
  },
  {
    id: 'earth-maul',
    name: 'Earth Maul',
    category: 'weapon',
    cost: 95,
    tier: 1,
    hunterAffinity: 'benzu',
    description: 'Slot 2 weapon. +100 max HP.',
    effect: { slot2WeaponId: 'earth-maul', modifiers: { maxHpBonus: 100 }, heal: 100 },
  },
  {
    id: 'lightning-bow',
    name: 'Lightning Bow',
    category: 'weapon',
    cost: 85,
    tier: 1,
    hunterAffinity: 'sereisa',
    description: 'Slot 2 weapon. +8% speed and damage.',
    effect: { slot2WeaponId: 'lightning-bow', modifiers: { speedMult: 0.08, damageMult: 0.08 } },
  },
  {
    id: 'mana-staff',
    name: 'Mana Staff',
    category: 'weapon',
    cost: 80,
    tier: 1,
    hunterAffinity: 'vesol',
    description: 'Slot 2 weapon. +15% spell damage.',
    effect: { slot2WeaponId: 'mana-staff', modifiers: { spellDamageMult: 0.15 } },
  },
  {
    id: 'aura-color-free',
    name: 'Aura Refit',
    category: 'cosmetic',
    cost: 0,
    tier: 1,
    cosmetic: true,
    description: 'Free cosmetic: brighter aura presentation.',
    effect: { modifiers: { auraScale: 0.08, cosmeticAura: 'refit' } },
  },
  {
    id: 'trail-refit-free',
    name: 'Trail Refit',
    category: 'cosmetic',
    cost: 0,
    tier: 2,
    cosmetic: true,
    description: 'Free cosmetic: stronger trail identity.',
    effect: { modifiers: { auraScale: 0.08, cosmeticAura: 'trail' } },
  },
];

export function createDefaultModifiers() {
  return { ...DEFAULT_MODIFIERS };
}

export function shouldQueueCardLevel(level) {
  return CARD_LEVELS.includes(level);
}

export function getCardById(cardId) {
  return CARD_POOL.find(card => card.id === cardId) || null;
}

export function getShopItemById(itemId) {
  return SHOP_ITEMS.find(item => item.id === itemId) || null;
}

export function getCardChoices(player, levelOverride = null) {
  if (!player) return [];

  const owned = new Set(player.ownedCards || []);
  const level = levelOverride || player.level;

  if (level === 2) return withoutOwned(GENERIC_STAT_CARDS.slice(0, 3), owned);
  if (level === 4) return withoutOwned(SPELL_MOD_CARDS.filter(card => card.level === 4 && card.hunterId === player.hunterId), owned);
  if (level === 5) {
    const hunterPassive = PASSIVE_CARDS.find(card => card.hunterId === player.hunterId);
    return withoutOwned([GENERIC_STAT_CARDS[0], GENERIC_STAT_CARDS[2], hunterPassive || PASSIVE_CARDS[4]], owned);
  }
  if (level === 6) return withoutOwned(SPELL_MOD_CARDS.filter(card => card.level === 6 && card.hunterId === player.hunterId), owned);
  if (level === 7) return withoutOwned(PATH_LOCK_CARDS, owned);
  if (level === 8) {
    const path = player.upgradePath || 'power';
    return withoutOwned(PATH_UPGRADE_CARDS.filter(card => card.path === path), owned);
  }
  if (level === 10) {
    const path = player.upgradePath || 'power';
    return withoutOwned(CAPSTONE_CARDS.filter(card => card.path === path), owned);
  }

  return [];
}

function withoutOwned(cards, owned) {
  return cards.filter(Boolean).filter(card => !owned.has(card.id));
}
